apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: akbota18/restfulcrud:v1.1.0
        command: ["/bin/bash","-c", "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver"]
        ports:
        - name: web
          containerPort: 8000
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: POSTGRES_USER
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: POSTGRES_HOST
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: SECRET_KEY