prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
  scrape_configs:
    - job_name: django
      scrape_interval: 10s
      static_configs:
    - targets:
    - localhost: 8000