---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: backend
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: akbota18/backend:v1
        name: service-back
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: /var/log/
            name: backend
        command: ["/bin/sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"]
      volumes:
        - name: backend
          hostPath:
            path: /var/log/